//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class AnalyzerResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal AnalyzerResources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnalyzerResources", typeof(AnalyzerResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string AllocSmallArraysOnStackDescription {
        get {
            return ResourceManager.GetString("AllocSmallArraysOnStackDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string AllocSmallArraysOnStackMessage {
        get {
            return ResourceManager.GetString("AllocSmallArraysOnStackMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string AllocSmallArraysOnStackTitle {
        get {
            return ResourceManager.GetString("AllocSmallArraysOnStackTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string DetectPLINQNopsDescription {
        get {
            return ResourceManager.GetString("DetectPLINQNopsDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string DetectPLINQNopsMessage {
        get {
            return ResourceManager.GetString("DetectPLINQNopsMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string DetectPLINQNopsTitle {
        get {
            return ResourceManager.GetString("DetectPLINQNopsTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string ExtractConstArrayDescription {
        get {
            return ResourceManager.GetString("ExtractConstArrayDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string ExtractConstArrayMessage {
        get {
            return ResourceManager.GetString("ExtractConstArrayMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string ExtractConstArrayTitle {
        get {
            return ResourceManager.GetString("ExtractConstArrayTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string OverrideStreamReadAsyncDescription {
        get {
            return ResourceManager.GetString("OverrideStreamReadAsyncDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string OverrideStreamReadAsyncMessage {
        get {
            return ResourceManager.GetString("OverrideStreamReadAsyncMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string OverrideStreamReadOrWriteAsyncTitle {
        get {
            return ResourceManager.GetString("OverrideStreamReadOrWriteAsyncTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string OverrideStreamWriteAsyncDescription {
        get {
            return ResourceManager.GetString("OverrideStreamWriteAsyncDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string OverrideStreamWriteAsyncMessage {
        get {
            return ResourceManager.GetString("OverrideStreamWriteAsyncMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Invocation on Dictionary can be simplified.
    /// </summary>
    internal static string PreferContainsKeyOrValueOverPropertyAccessTitle {
        get {
            return ResourceManager.GetString("PreferContainsKeyOrValueOverPropertyAccessTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &apos;IDictionary&lt;,&gt;&apos; offers a &apos;ContainsKey&apos; method which should be preferred instead of accessing the &apos;Keys&apos; property and calling &apos;Contains&apos; on that.
    /// </summary>
    internal static string PreferContainsKeyOverPropertyAccessMessage {
        get {
            return ResourceManager.GetString("PreferContainsKeyOverPropertyAccessMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &apos;ContainsKey&apos; does not incur the same overhead as calling the LINQ &apos;Contains&apos; method on the &apos;Keys&apos; collection..
    /// </summary>
    internal static string PreferContainsKeyOverPropertyDescription {
        get {
            return ResourceManager.GetString("PreferContainsKeyOverPropertyDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &apos;Dictionary&lt;,&gt;&apos; offers a &apos;ContainsValue&apos; method which should be preferred instead of accessing the &apos;Values&apos; property and calling &apos;Contains&apos; on that.
    /// </summary>
    internal static string PreferContainsValueOverPropertyAccessMessage {
        get {
            return ResourceManager.GetString("PreferContainsValueOverPropertyAccessMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &apos;ContainsValue&apos; does not incur the same overhead as calling the LINQ &apos;Contains&apos; method on the &apos;Values&apos; collection..
    /// </summary>
    internal static string PreferContainsValueOverPropertyDescription {
        get {
            return ResourceManager.GetString("PreferContainsValueOverPropertyDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This substring invocation can be replaced with an &apos;AsSpan().Slice()&apos; invocation..
    /// </summary>
    internal static string PreferSpanArgumentOverSubstringDescription {
        get {
            return ResourceManager.GetString("PreferSpanArgumentOverSubstringDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Substring invocation &apos;{0}&apos; can be made more efficient.
    /// </summary>
    internal static string PreferSpanArgumentOverSubstringMessage {
        get {
            return ResourceManager.GetString("PreferSpanArgumentOverSubstringMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Substring invocation can be made more efficient.
    /// </summary>
    internal static string PreferSpanArgumentOverSubstringTitle {
        get {
            return ResourceManager.GetString("PreferSpanArgumentOverSubstringTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string ProvideCorrectArgumentToEnumHasFlagDescription {
        get {
            return ResourceManager.GetString("ProvideCorrectArgumentToEnumHasFlagDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string ProvideCorrectArgumentToEnumHasFlagMessageNotFlags {
        get {
            return ResourceManager.GetString("ProvideCorrectArgumentToEnumHasFlagMessageNotFlags", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string ProvideCorrectArgumentToEnumHasFlagTitle {
        get {
            return ResourceManager.GetString("ProvideCorrectArgumentToEnumHasFlagTitle", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string TaskDelayUseCancellationTokenInWhenAnyClauseDescription {
        get {
            return ResourceManager.GetString("TaskDelayUseCancellationTokenInWhenAnyClauseDescription", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string TaskDelayUseCancellationTokenInWhenAnyClauseMessage {
        get {
            return ResourceManager.GetString("TaskDelayUseCancellationTokenInWhenAnyClauseMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string TaskDelayUseCancellationTokenInWhenAnyClauseTitle {
        get {
            return ResourceManager.GetString("TaskDelayUseCancellationTokenInWhenAnyClauseTitle", resourceCulture);
        }
    }
}
